services:
  jpa-minio:
    networks:
      - default
      - pangolin

  jpa-server:
    image: ghcr.io/clashwithjpa/server:${JPA_IMAGE_TAG:-latest}
    pull_policy: always
    networks:
      - default
      - pangolin

  jpa-web:
    image: ghcr.io/clashwithjpa/web:${JPA_IMAGE_TAG:-latest}
    pull_policy: always
    networks:
      - default
      - pangolin

  jpa-db:
    networks:
      - default
      - pangolin

networks:
  pangolin:
    name: pangolin
    external: true
