/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetUserQueryResponse, GetUser401, GetUser500 } from "../models/GetUser.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, CreateBaseQueryOptions, CreateQueryResult } from "@tanstack/svelte-query";
import { getUser } from "../clients/getUser.ts";
import { createQuery, queryOptions } from "@tanstack/svelte-query";

export const getUserQueryKey = () => [{ url: "/user" }] as const;

export type GetUserQueryKey = ReturnType<typeof getUserQueryKey>;

export function getUserQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {
    const queryKey = getUserQueryKey();
    return queryOptions<GetUserQueryResponse, ResponseErrorConfig<GetUser401 | GetUser500>, GetUserQueryResponse, typeof queryKey>({
        queryKey,
        queryFn: async ({ signal }) => {
            return getUser({ ...config, signal: config.signal ?? signal });
        },
    });
}

/**
 * @description [Authenticated] Fetches the current user's data.
 * {@link /user}
 */
export function createGetUser<TData = GetUserQueryResponse, TQueryData = GetUserQueryResponse, TQueryKey extends QueryKey = GetUserQueryKey>(
    options: {
        query?: Partial<CreateBaseQueryOptions<GetUserQueryResponse, ResponseErrorConfig<GetUser401 | GetUser500>, TData, TQueryData, TQueryKey>> & {
            client?: QueryClient;
        };
        client?: Partial<RequestConfig> & { client?: Client };
    } = {},
) {
    const { query: queryConfig = {}, client: config = {} } = options ?? {};
    const { client: queryClient, ...resolvedOptions } = queryConfig;
    const queryKey = resolvedOptions?.queryKey ?? getUserQueryKey();

    const query = createQuery(
        {
            ...getUserQueryOptions(config),
            ...resolvedOptions,
            queryKey,
        } as unknown as CreateBaseQueryOptions,
        queryClient,
    ) as CreateQueryResult<TData, ResponseErrorConfig<GetUser401 | GetUser500>> & { queryKey: TQueryKey };

    query.queryKey = queryKey as TQueryKey;

    return query;
}
