/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetCOCPlayerQueryResponse, GetCOCPlayerPathParams, GetCOCPlayer500 } from "../models/GetCOCPlayer.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, CreateBaseQueryOptions, CreateQueryResult } from "@tanstack/svelte-query";
import { getCOCPlayer } from "../clients/getCOCPlayer.ts";
import { createQuery, queryOptions } from "@tanstack/svelte-query";

export const getCOCPlayerQueryKey = (tag: GetCOCPlayerPathParams["tag"]) => [{ url: "/coc/player/:tag", params: { tag: tag } }] as const;

export type GetCOCPlayerQueryKey = ReturnType<typeof getCOCPlayerQueryKey>;

export function getCOCPlayerQueryOptions(tag: GetCOCPlayerPathParams["tag"], config: Partial<RequestConfig> & { client?: Client } = {}) {
    const queryKey = getCOCPlayerQueryKey(tag);
    return queryOptions<GetCOCPlayerQueryResponse, ResponseErrorConfig<GetCOCPlayer500>, GetCOCPlayerQueryResponse, typeof queryKey>({
        enabled: !!tag,
        queryKey,
        queryFn: async ({ signal }) => {
            return getCOCPlayer(tag, { ...config, signal: config.signal ?? signal });
        },
    });
}

/**
 * @description [Authenticated] Fetches a Clash of Clans player's data by their tag. The tag must start with #.
 * {@link /coc/player/:tag}
 */
export function createGetCOCPlayer<
    TData = GetCOCPlayerQueryResponse,
    TQueryData = GetCOCPlayerQueryResponse,
    TQueryKey extends QueryKey = GetCOCPlayerQueryKey,
>(
    tag: GetCOCPlayerPathParams["tag"],
    options: {
        query?: Partial<CreateBaseQueryOptions<GetCOCPlayerQueryResponse, ResponseErrorConfig<GetCOCPlayer500>, TData, TQueryData, TQueryKey>> & {
            client?: QueryClient;
        };
        client?: Partial<RequestConfig> & { client?: Client };
    } = {},
) {
    const { query: queryConfig = {}, client: config = {} } = options ?? {};
    const { client: queryClient, ...resolvedOptions } = queryConfig;
    const queryKey = resolvedOptions?.queryKey ?? getCOCPlayerQueryKey(tag);

    const query = createQuery(
        {
            ...getCOCPlayerQueryOptions(tag, config),
            ...resolvedOptions,
            queryKey,
        } as unknown as CreateBaseQueryOptions,
        queryClient,
    ) as CreateQueryResult<TData, ResponseErrorConfig<GetCOCPlayer500>> & { queryKey: TQueryKey };

    query.queryKey = queryKey as TQueryKey;

    return query;
}
