/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
    PostCOCPlayerVerifyMutationRequest,
    PostCOCPlayerVerifyMutationResponse,
    PostCOCPlayerVerifyPathParams,
    PostCOCPlayerVerify500,
} from "../models/PostCOCPlayerVerify.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { CreateMutationOptions, QueryClient } from "@tanstack/svelte-query";
import { postCOCPlayerVerify } from "../clients/postCOCPlayerVerify.ts";
import { createMutation } from "@tanstack/svelte-query";

export const postCOCPlayerVerifyMutationKey = () => [{ url: "/coc/player/:tag/verifytoken" }] as const;

export type PostCOCPlayerVerifyMutationKey = ReturnType<typeof postCOCPlayerVerifyMutationKey>;

/**
 * @description [Authenticated] Verifies a Clash of Clans player's API token.
 * {@link /coc/player/:tag/verifytoken}
 */
export function createPostCOCPlayerVerify<TContext>(
    options: {
        mutation?: CreateMutationOptions<
            PostCOCPlayerVerifyMutationResponse,
            ResponseErrorConfig<PostCOCPlayerVerify500>,
            { tag: PostCOCPlayerVerifyPathParams["tag"]; data: PostCOCPlayerVerifyMutationRequest },
            TContext
        > & { client?: QueryClient };
        client?: Partial<RequestConfig<PostCOCPlayerVerifyMutationRequest>> & { client?: Client };
    } = {},
) {
    const { mutation = {}, client: config = {} } = options ?? {};
    const { client: queryClient, ...mutationOptions } = mutation;
    const mutationKey = mutationOptions?.mutationKey ?? postCOCPlayerVerifyMutationKey();

    return createMutation<
        PostCOCPlayerVerifyMutationResponse,
        ResponseErrorConfig<PostCOCPlayerVerify500>,
        { tag: PostCOCPlayerVerifyPathParams["tag"]; data: PostCOCPlayerVerifyMutationRequest },
        TContext
    >(
        {
            mutationFn: async ({ tag, data }) => {
                return postCOCPlayerVerify(tag, data, config);
            },
            mutationKey,
            ...mutationOptions,
        },
        queryClient,
    );
}
