/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetJPAClansQueryResponse, GetJPAClans500 } from "../models/GetJPAClans.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, CreateBaseQueryOptions, CreateQueryResult } from "@tanstack/svelte-query";
import { getJPAClans } from "../clients/getJPAClans.ts";
import { createQuery, queryOptions } from "@tanstack/svelte-query";

export const getJPAClansQueryKey = () => [{ url: "/coc/jpa/clans" }] as const;

export type GetJPAClansQueryKey = ReturnType<typeof getJPAClansQueryKey>;

export function getJPAClansQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {
    const queryKey = getJPAClansQueryKey();
    return queryOptions<GetJPAClansQueryResponse, ResponseErrorConfig<GetJPAClans500>, GetJPAClansQueryResponse, typeof queryKey>({
        queryKey,
        queryFn: async ({ signal }) => {
            return getJPAClans({ ...config, signal: config.signal ?? signal });
        },
    });
}

/**
 * @description [Authenticated] Fetches all JPA clans.
 * {@link /coc/jpa/clans}
 */
export function createGetJPAClans<
    TData = GetJPAClansQueryResponse,
    TQueryData = GetJPAClansQueryResponse,
    TQueryKey extends QueryKey = GetJPAClansQueryKey,
>(
    options: {
        query?: Partial<CreateBaseQueryOptions<GetJPAClansQueryResponse, ResponseErrorConfig<GetJPAClans500>, TData, TQueryData, TQueryKey>> & {
            client?: QueryClient;
        };
        client?: Partial<RequestConfig> & { client?: Client };
    } = {},
) {
    const { query: queryConfig = {}, client: config = {} } = options ?? {};
    const { client: queryClient, ...resolvedOptions } = queryConfig;
    const queryKey = resolvedOptions?.queryKey ?? getJPAClansQueryKey();

    const query = createQuery(
        {
            ...getJPAClansQueryOptions(config),
            ...resolvedOptions,
            queryKey,
        } as unknown as CreateBaseQueryOptions,
        queryClient,
    ) as CreateQueryResult<TData, ResponseErrorConfig<GetJPAClans500>> & { queryKey: TQueryKey };

    query.queryKey = queryKey as TQueryKey;

    return query;
}
