/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetCOCClanCWLGroupQueryResponse, GetCOCClanCWLGroupPathParams, GetCOCClanCWLGroup500 } from "../models/GetCOCClanCWLGroup.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, CreateBaseQueryOptions, CreateQueryResult } from "@tanstack/svelte-query";
import { getCOCClanCWLGroup } from "../clients/getCOCClanCWLGroup.ts";
import { createQuery, queryOptions } from "@tanstack/svelte-query";

export const getCOCClanCWLGroupQueryKey = (tag: GetCOCClanCWLGroupPathParams["tag"]) =>
    [{ url: "/coc/clan/:tag/currentwar/leaguegroup", params: { tag: tag } }] as const;

export type GetCOCClanCWLGroupQueryKey = ReturnType<typeof getCOCClanCWLGroupQueryKey>;

export function getCOCClanCWLGroupQueryOptions(tag: GetCOCClanCWLGroupPathParams["tag"], config: Partial<RequestConfig> & { client?: Client } = {}) {
    const queryKey = getCOCClanCWLGroupQueryKey(tag);
    return queryOptions<
        GetCOCClanCWLGroupQueryResponse,
        ResponseErrorConfig<GetCOCClanCWLGroup500>,
        GetCOCClanCWLGroupQueryResponse,
        typeof queryKey
    >({
        enabled: !!tag,
        queryKey,
        queryFn: async ({ signal }) => {
            return getCOCClanCWLGroup(tag, { ...config, signal: config.signal ?? signal });
        },
    });
}

/**
 * @description [Authenticated] Fetches a Clash of Clans clan's current CWL league group by its tag. The tag must start with #.
 * {@link /coc/clan/:tag/currentwar/leaguegroup}
 */
export function createGetCOCClanCWLGroup<
    TData = GetCOCClanCWLGroupQueryResponse,
    TQueryData = GetCOCClanCWLGroupQueryResponse,
    TQueryKey extends QueryKey = GetCOCClanCWLGroupQueryKey,
>(
    tag: GetCOCClanCWLGroupPathParams["tag"],
    options: {
        query?: Partial<
            CreateBaseQueryOptions<GetCOCClanCWLGroupQueryResponse, ResponseErrorConfig<GetCOCClanCWLGroup500>, TData, TQueryData, TQueryKey>
        > & { client?: QueryClient };
        client?: Partial<RequestConfig> & { client?: Client };
    } = {},
) {
    const { query: queryConfig = {}, client: config = {} } = options ?? {};
    const { client: queryClient, ...resolvedOptions } = queryConfig;
    const queryKey = resolvedOptions?.queryKey ?? getCOCClanCWLGroupQueryKey(tag);

    const query = createQuery(
        {
            ...getCOCClanCWLGroupQueryOptions(tag, config),
            ...resolvedOptions,
            queryKey,
        } as unknown as CreateBaseQueryOptions,
        queryClient,
    ) as CreateQueryResult<TData, ResponseErrorConfig<GetCOCClanCWLGroup500>> & { queryKey: TQueryKey };

    query.queryKey = queryKey as TQueryKey;

    return query;
}
