CREATE TYPE "public"."app_role" AS ENUM('admin', 'cwl_manager', 'join_manager', 'clan_manager', 'user_manager', 'rule_manager', 'setting_manager', 'base_manager', 'coc_account_manager');
--> statement-breakpoint

CREATE TYPE "public"."join_status" AS ENUM('accepted', 'rejected', 'pending');
--> statement-breakpoint


CREATE TABLE "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"discord_id" text NOT NULL,
	"is_active" boolean NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_discord_id_key" UNIQUE("discord_id")
);
--> statement-breakpoint
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint


CREATE TABLE "bases" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bases_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"level" smallint NOT NULL,
	"layout_link" text NOT NULL,
	"base_link" text NOT NULL,
	CONSTRAINT "bases_level_key" UNIQUE("level")
);
--> statement-breakpoint
ALTER TABLE "bases" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint


CREATE TABLE "cwl_clans" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cwl_clans_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"clan_tag" text NOT NULL,
	"clan_name" text NOT NULL,
	CONSTRAINT "cwl_clans_clan_tag_key" UNIQUE("clan_tag")
);
--> statement-breakpoint
ALTER TABLE "cwl_clans" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint


CREATE TABLE "clans" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "clans_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"clan_code" text NOT NULL,
	"clan_name" text NOT NULL,
	"clan_level" smallint NOT NULL,
	"clan_tag" text NOT NULL,
	"attacks_requirement" integer,
	"donations_requirement" integer,
	"clangames_requirement" integer,
	"clan_data" jsonb,
	"clan_current_war" jsonb
);
--> statement-breakpoint
ALTER TABLE "clans" ENABLE ROW LEVEL SECURITY
;--> statement-breakpoint


CREATE TABLE "cwl_applications" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cwl_applications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"discord_id" text NOT NULL,
	"discord_username" text NOT NULL,
	"account_name" text NOT NULL,
	"account_tag" text NOT NULL,
	"account_clan" text NOT NULL,
	"account_weight" integer NOT NULL,
	"assigned_clan" text NOT NULL,
	"month" text NOT NULL,
	"year" integer NOT NULL,
	"preference_num" smallint NOT NULL,
	"applied_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "cwl_applications" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint


CREATE TABLE "user_roles" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"role" "app_role" NOT NULL,
	CONSTRAINT "user_roles_user_id_role_key" UNIQUE("user_id","role")
);
--> statement-breakpoint
ALTER TABLE "user_roles" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint


CREATE TABLE "coc_accounts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "coc_accounts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"discord_id" text NOT NULL,
	"account_tag" text NOT NULL,
	CONSTRAINT "coc_accounts_account_tag_key" UNIQUE("account_tag")
);
--> statement-breakpoint
ALTER TABLE "coc_accounts" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint


CREATE TABLE "join_applications" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "join_applications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"account_tag" text NOT NULL,
	"player_data" jsonb NOT NULL,
	"discord_username" text NOT NULL,
	"discord_id" text NOT NULL,
	"status" "join_status" NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "join_applications_account_tag_key" UNIQUE("account_tag")
);
--> statement-breakpoint
ALTER TABLE "join_applications" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint


CREATE TABLE "settings" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text NOT NULL,
	"type" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "settings" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint