/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
    ApplyUserAccountMutationRequest,
    ApplyUserAccountMutationResponse,
    ApplyUserAccount400,
    ApplyUserAccount401,
    ApplyUserAccount409,
    ApplyUserAccount500,
} from "../models/ApplyUserAccount.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getApplyUserAccountUrl() {
    const res = { method: "POST", url: `/user/accounts/apply` as const };
    return res;
}

/**
 * @description [Authenticated] Submits a clan application for a Clash of Clans account after verifying ownership.
 * {@link /user/accounts/apply}
 */
export async function applyUserAccount(
    data: ApplyUserAccountMutationRequest,
    config: Partial<RequestConfig<ApplyUserAccountMutationRequest>> & { client?: Client } = {},
) {
    const { client: request = fetch, ...requestConfig } = config;

    const requestData = data;

    const res = await request<
        ApplyUserAccountMutationResponse,
        ResponseErrorConfig<ApplyUserAccount400 | ApplyUserAccount401 | ApplyUserAccount409 | ApplyUserAccount500>,
        ApplyUserAccountMutationRequest
    >({ method: "POST", url: getApplyUserAccountUrl().url.toString(), data: requestData, ...requestConfig });
    return res.data;
}
