/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetCOCClanQueryResponse, GetCOCClanPathParams, GetCOCClan500 } from "../models/GetCOCClan.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetCOCClanUrl(tag: GetCOCClanPathParams["tag"]) {
    const res = { method: "GET", url: `/coc/clan/${tag}` as const };
    return res;
}

/**
 * @description [Public] Fetches a Clash of Clans clan's data by its tag. The tag must start with #.
 * {@link /coc/clan/:tag}
 */
export async function getCOCClan(tag: GetCOCClanPathParams["tag"], config: Partial<RequestConfig> & { client?: Client } = {}) {
    const { client: request = fetch, ...requestConfig } = config;

    const res = await request<GetCOCClanQueryResponse, ResponseErrorConfig<GetCOCClan500>, unknown>({
        method: "GET",
        url: getGetCOCClanUrl(tag).url.toString(),
        ...requestConfig,
    });
    return res.data;
}
