/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
    GetCOCPlayerBattleLogQueryResponse,
    GetCOCPlayerBattleLogPathParams,
    GetCOCPlayerBattleLog500,
} from "../models/GetCOCPlayerBattleLog.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetCOCPlayerBattleLogUrl(tag: GetCOCPlayerBattleLogPathParams["tag"]) {
    const res = { method: "GET", url: `/coc/player/${tag}/battlelog` as const };
    return res;
}

/**
 * @description [Authenticated] Fetches a Clash of Clans player's battle log by their tag. The tag must start with #.
 * {@link /coc/player/:tag/battlelog}
 */
export async function getCOCPlayerBattleLog(tag: GetCOCPlayerBattleLogPathParams["tag"], config: Partial<RequestConfig> & { client?: Client } = {}) {
    const { client: request = fetch, ...requestConfig } = config;

    const res = await request<GetCOCPlayerBattleLogQueryResponse, ResponseErrorConfig<GetCOCPlayerBattleLog500>, unknown>({
        method: "GET",
        url: getGetCOCPlayerBattleLogUrl(tag).url.toString(),
        ...requestConfig,
    });
    return res.data;
}
