/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetCOCClanCurrentWarQueryResponse, GetCOCClanCurrentWarPathParams, GetCOCClanCurrentWar500 } from "../models/GetCOCClanCurrentWar.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetCOCClanCurrentWarUrl(tag: GetCOCClanCurrentWarPathParams["tag"]) {
    const res = { method: "GET", url: `/coc/clan/${tag}/currentwar` as const };
    return res;
}

/**
 * @description [Public] Fetches a Clash of Clans clan's current war by its tag. The tag must start with #.
 * {@link /coc/clan/:tag/currentwar}
 */
export async function getCOCClanCurrentWar(tag: GetCOCClanCurrentWarPathParams["tag"], config: Partial<RequestConfig> & { client?: Client } = {}) {
    const { client: request = fetch, ...requestConfig } = config;

    const res = await request<GetCOCClanCurrentWarQueryResponse, ResponseErrorConfig<GetCOCClanCurrentWar500>, unknown>({
        method: "GET",
        url: getGetCOCClanCurrentWarUrl(tag).url.toString(),
        ...requestConfig,
    });
    return res.data;
}
