/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetCOCClanCWLGroupQueryResponse, GetCOCClanCWLGroupPathParams, GetCOCClanCWLGroup500 } from "../models/GetCOCClanCWLGroup.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetCOCClanCWLGroupUrl(tag: GetCOCClanCWLGroupPathParams["tag"]) {
    const res = { method: "GET", url: `/coc/clan/${tag}/currentwar/leaguegroup` as const };
    return res;
}

/**
 * @description [Authenticated] Fetches a Clash of Clans clan's current CWL league group by its tag. The tag must start with #.
 * {@link /coc/clan/:tag/currentwar/leaguegroup}
 */
export async function getCOCClanCWLGroup(tag: GetCOCClanCWLGroupPathParams["tag"], config: Partial<RequestConfig> & { client?: Client } = {}) {
    const { client: request = fetch, ...requestConfig } = config;

    const res = await request<GetCOCClanCWLGroupQueryResponse, ResponseErrorConfig<GetCOCClanCWLGroup500>, unknown>({
        method: "GET",
        url: getGetCOCClanCWLGroupUrl(tag).url.toString(),
        ...requestConfig,
    });
    return res.data;
}
