/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetCOCCWLWarQueryResponse, GetCOCCWLWarPathParams, GetCOCCWLWar500 } from "../models/GetCOCCWLWar.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetCOCCWLWarUrl(warTag: GetCOCCWLWarPathParams["warTag"]) {
    const res = { method: "GET", url: `/coc/cwl/wars/${warTag}` as const };
    return res;
}

/**
 * @description [Authenticated] Fetches a CWL war's details by its war tag. The tag must start with #.
 * {@link /coc/cwl/wars/:warTag}
 */
export async function getCOCCWLWar(warTag: GetCOCCWLWarPathParams["warTag"], config: Partial<RequestConfig> & { client?: Client } = {}) {
    const { client: request = fetch, ...requestConfig } = config;

    const res = await request<GetCOCCWLWarQueryResponse, ResponseErrorConfig<GetCOCCWLWar500>, unknown>({
        method: "GET",
        url: getGetCOCCWLWarUrl(warTag).url.toString(),
        ...requestConfig,
    });
    return res.data;
}
