/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetJPAClansQueryResponse, GetJPAClans500 } from "../models/GetJPAClans.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetJPAClansUrl() {
    const res = { method: "GET", url: `/coc/jpa/clans` as const };
    return res;
}

/**
 * @description [Authenticated] Fetches all JPA clans.
 * {@link /coc/jpa/clans}
 */
export async function getJPAClans(config: Partial<RequestConfig> & { client?: Client } = {}) {
    const { client: request = fetch, ...requestConfig } = config;

    const res = await request<GetJPAClansQueryResponse, ResponseErrorConfig<GetJPAClans500>, unknown>({
        method: "GET",
        url: getGetJPAClansUrl().url.toString(),
        ...requestConfig,
    });
    return res.data;
}
