/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type { LoginQueryResponse } from "../models/Login.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getLoginUrl() {
    const res = { method: "GET", url: `/login` as const };
    return res;
}

/**
 * @description [Public] Use this only for backend/scalar usage. For frontend, authClient should be used.
 * {@link /login}
 */
export async function login(config: Partial<RequestConfig> & { client?: Client } = {}) {
    const { client: request = fetch, ...requestConfig } = config;

    const res = await request<LoginQueryResponse, ResponseErrorConfig<Error>, unknown>({
        method: "GET",
        url: getLoginUrl().url.toString(),
        ...requestConfig,
    });
    return res.data;
}
