/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetCOCClanMembersPathParams = {
    /**
     * @minLength 1
     * @pattern ^#.*
     * @type string
     */
    tag: string;
};

export const itemsRoleEnum = {
    member: "member",
    admin: "admin",
    coLeader: "coLeader",
    leader: "leader",
} as const;

export type ItemsRoleEnumKey = (typeof itemsRoleEnum)[keyof typeof itemsRoleEnum];

/**
 * @description Successful response with the clan\'s members.
 */
export type GetCOCClanMembers200 = {
    /**
     * @type boolean
     */
    success: true;
    /**
     * @type object
     */
    data: {
        /**
         * @type object
         */
        clanMembers: {
            /**
             * @type array
             */
            items: {
                /**
                 * @type string
                 */
                name: string;
                /**
                 * @type string
                 */
                tag: string;
                /**
                 * @type string
                 */
                role: ItemsRoleEnumKey;
                /**
                 * @type number
                 */
                expLevel: number;
                /**
                 * @type number
                 */
                townHallLevel: number;
                /**
                 * @type object | undefined
                 */
                leagueTier?: {
                    /**
                     * @type number
                     */
                    id: number;
                    /**
                     * @type string
                     */
                    name: string;
                    /**
                     * @type object
                     */
                    iconUrls: {
                        /**
                         * @type string
                         */
                        small: string;
                        /**
                         * @type string
                         */
                        large: string;
                    };
                };
                /**
                 * @type object | undefined
                 */
                builderBaseLeague?: {
                    /**
                     * @type number
                     */
                    id: number;
                    /**
                     * @type string
                     */
                    name: string;
                };
                /**
                 * @type number
                 */
                trophies: number;
                /**
                 * @type number | undefined
                 */
                builderBaseTrophies?: number;
                /**
                 * @type number
                 */
                clanRank: number;
                /**
                 * @type number
                 */
                previousClanRank: number;
                /**
                 * @type number
                 */
                donations: number;
                /**
                 * @type number
                 */
                donationsReceived: number;
                /**
                 * @type object | undefined
                 */
                playerHouse?: {
                    /**
                     * @type array
                     */
                    elements: {
                        /**
                         * @type string
                         */
                        type: string;
                        /**
                         * @type number
                         */
                        id: number;
                    }[];
                };
            }[];
            /**
             * @type object
             */
            paging: {
                /**
                 * @type object | undefined
                 */
                cursors?: {
                    /**
                     * @type string | undefined
                     */
                    after?: string;
                    /**
                     * @type string | undefined
                     */
                    before?: string;
                };
            };
        };
    };
};

/**
 * @description Server error response when fetching clan members fails.
 */
export type GetCOCClanMembers500 = {
    /**
     * @type boolean
     */
    success: false;
    error:
        | string
        | {
              [key: string]: any;
          };
};

export type GetCOCClanMembersQueryResponse = GetCOCClanMembers200;

export type GetCOCClanMembersQuery = {
    Response: GetCOCClanMembers200;
    PathParams: GetCOCClanMembersPathParams;
    Errors: GetCOCClanMembers500;
};
