/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Successful response with a welcome message.
 */
export type GetRoot200 = {
    /**
     * @type boolean
     */
    success: true;
    /**
     * @type object
     */
    data: {
        /**
         * @type string
         */
        message: string;
    };
};

export type GetRootQueryResponse = GetRoot200;

export type GetRootQuery = {
    Response: GetRoot200;
    Errors: any;
};
