/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Successful response with a logout message.
 */
export type Logout200 = {
    /**
     * @type boolean
     */
    success: true;
    /**
     * @type object
     */
    data: {
        /**
         * @type string
         */
        message: string;
    };
};

/**
 * @description Server error response when logging out fails.
 */
export type Logout500 = {
    /**
     * @type boolean
     */
    success: false;
    error:
        | string
        | {
              [key: string]: any;
          };
};

export type LogoutMutationResponse = Logout200;

export type LogoutMutation = {
    Response: Logout200;
    Errors: Logout500;
};
